name: piss
version: '1.0'
main: net.nar1nari.piss.Piss
api-version: '1.21'
folia-supported: true
authors: [ mossadceo ]
description: A plugin you need to relieve yourself.
commands:
  piss:
    description: Start peeing
    usage: /piss [reload]
    permission: piss.use
permissions:
  piss.use:
    description: Allows player to use /piss
    default: true
  piss.reload:
    description: Allows player to reload plugin config
    default: op
